#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
#!/usr/bin/env bash
#Prints Holberton School to stdout 10 times with a while loop.
count=1
word="Holberton School"
while [ $count -lt 11 ];
do
    echo "$word"
    if [ $count -eq 9 ];
    then
	echo "Hi"
    fi
    count=$(( count + 1 ))
done
