#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
count=1
word="Holberton School"
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]
    then
    echo "bad luck"
    elif [ $count -eq 8 ]
    then
    echo "good luck"
    else
    echo "$word"
    fi
    count=$(( count + 1 ))
done
