#!/usr/bin/env bash
# This script is displaying numbers
hours=0
while [ $hours -le 12 ];
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -le 59 ]; do
	echo "$minutes"
	minutes=$((minutes + 1))
	done
    hours=$((hours + 1))
done
