#!/usr/bin/env bash
# This script display the files in the current directory
for num in {1..100}; do
    if [ $((num % 3)) -eq 0 ] && [ $((num % 5)) -eq 0 ]; then
	echo "FizzBuzz"
    fi
    if [ $((num % 3)) -eq 0 ]; then
	echo "Fizz"
    elif [ $((num % 5)) -eq 0 ]; then
	echo "Buzz"
    else
	echo "$num"
    fi
done
